name: Verifications

on:
  push:
    branches:
      - "*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Unit Tests
        run: ./mvnw test

  docker-build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      ### Runs if the branch is not main
      - name: Build Docker image
        if: github.ref != 'refs/heads/main'
        run: docker buildx build . -t 2025-devops-cd
      ### End

      ### Runs only if the branch is main
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker buildx build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/2025-devops-cd:latest --push
      ### End

  documentation-build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate Documentation
        run: ./mvnw javadoc:javadoc

      ### Runs only if the branch is main
      - name : Deploy documentation on netlify
        uses : actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with : 
          name : documentation
          path : target/site/apidocs/

  deploy-render:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger render deployment
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  deploy-documentation:
    runs-on : ubuntu-latest
    needs : documentation-build
    if : github.ref == 'refs/heads/main'
    steps :
      - name : Checkout code 
        uses : actions/checkout@v3
      
      - name : Dowload Documentation
        uses : actions/download-artifact@v4
        with :
          name : documentation
          path : documentation

      - name : Install Netlify CLI
        run : npm install -g netlify-cli
      
      - name : Deploy Documentation 
        env : 
          NETLIFY_AUTH_TOKEN : ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run : netlify deploy -p --dir=documentation --site=$NETLIFY_SITE_ID --prod